### ISSUE TITLE
Error while trying to encrypt a value

### ISSUE THREAD

**Issue by Killy85** [megalord/lua-resty-fernet#1]
Hey,

Lua version -> Lua 5.1.5
Openresty -> openresty/1.15.8.3

I kind of a newbie to lua so i followed an advice and i've installed luajit 2.1 which seems to be used there.

As I tried to use that lib, I bumped into an error I don't really know how to correct and I'm thinking about a compatibility issue.

So, what I try to do is the following:

```local fernet = require "resty.fernet"
local key = fernet:generate_key()
local f = fernet:new(key)
local token, err = f:encrypt("secret")
print(token)
local secret, err = f:decrypt(token)
print(secret)
```

It follow the documentation on how to get started, but the following error is thrown:

```2020/07/22 18:38:26 [warn] 15308#15308: *2 [lua] _G write guard:12: __newindex(): writing a global Lua variable ('bytes') which may lead to race conditions between concurrent requests, so prefer the use of 'local' variables
stack traceback:
        /usr/local/share/lua/5.1/resty/fernet.lua:35: in function 'pack_int'
        /usr/local/share/lua/5.1/resty/fernet.lua:98: in function 'encrypt'
        resty.lua:7: in function 'file_gen'
        init_worker_by_lua:45: in function <init_worker_by_lua:43>
        [C]: in function 'xpcall'
        init_worker_by_lua:52: in function <init_worker_by_lua:50>, context: ngx.timer
ERROR: /usr/local/share/lua/5.1/resty/hmac.lua:93: /usr/local/openresty/luajit/lib/libluajit-5.1.so.2: undefined symbol: HMAC_CTX_init
```

So it seems the lib is not compatible with libffi embedded in open resty 1.15.*

I've tried with a version below 1.13 and it worked, but the rest of my project isn't, so that's not an option for me.

Thanks in advance for your help

**Comment by player-two** [comment]
Hey there, this is an issue with the hmac dependency.  As you can see, lua-resty-hmac uses the C ffi to call that function here: https://github.com/erento/lua-resty-hmac/blob/master/lib/resty/hmac.lua#L93

I don't have time at the moment to boot up a full openresty environment, but you might start by checking of the openssl version changed.

```
$ man hmac | rg -C1 HMAC_CTX_init
HISTORY
       HMAC_CTX_init() was replaced with HMAC_CTX_reset() in OpenSSL 1.1.0.

```

Naturally that won't fix the issue, but we'd be confident we know what happened between 1.13 and 1.15 to break this.  If this hunch is right, the fix would either happen in that hmac lib, or I'd have to switch it out for another that works.  Let me know what you find!

**Comment by Killy85** [comment]
Hello,

First of all, thanks for you help!

It was that, OpenSSL function that changed name, so I did a fork you can find here (https://github.com/lengow/lua-resty-hmac)

And now everything is working smoothly !

Thank you again,
